
version: '3.8'


services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 230188
      MYSQL_DATABASE: crm_assinador
      MYSQL_USER: dev_001
      MYSQL_PASSWORD: 230188
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:

  db_data:
